### ISSUE TITLE
Not working with variants

### ISSUE THREAD

**Issue by gaertnermarkus** [eComStyle-de/AntiPreisalarm#1]
The Version 1.0.1 does not work correct with variants. On parent, the pricealarm ist disabled.
But after a variant is select, the pricealarm ist still available / visible.

EE 6.1.1, 
unmodfied child of flow 3.0.2

**Comment by Josef-A-Puckl** [comment]
Hi, 
da wir, denke ich, beide deutsch sind (wie auch die meisten Nutzer dieses Moduls) antworte ich in deutscher Sprache. Ich hoffe das ist ok :-) 

In meiner EE 6.1.3 Testumgebung läuft das Modul einwandfrei. 
Bei Varianten wird beim Vater nie der Preisalarm gezeigt, egal ob mit oder ohne Modul (es sei denn, der Vater ist kaufbar).  

Ich denke, das Modul wurde nicht richtig via Composer installiert, wie auch Deine zweite Fehlermeldung zeigt: https://github.com/eComStyle/AntiPreisalarm/issues/2

**Comment by gaertnermarkus** [comment]
Hallo,  ja stimmt. Das Modul war nicht per Composer installiert. Mal sehen wem ich da auf die Finger klopfen muss.
